# Generated by Django 3.2.8 on 2021-12-06 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botenv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botenv',
            old_name='uid',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='botitem',
            old_name='envid',
            new_name='env',
        ),
    ]
