name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Heroku Container registry
      env: 
        HEROKU_EMAIL_ADDRESS: "zhangchi211@mails.ucas.ac.cn"
      run: heroku login 
    - name: Connect
      env:
        HEROKU_EMAIL_ADDRESS: "zhangchi211@mails.ucas.ac.cn"
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku git:remote -a murmuring-springs-71288
    - name: Build and push
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: git push heroku :refs/heads/main