name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Heroku login credentials
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          EOF
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: "zhangchi211@mails.ucas.ac.cn"
      - name: Connect
        env:
          HEROKU_EMAIL_ADDRESS: "zhangchi211@mails.ucas.ac.cn"
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku git:remote -a murmuring-springs-71288
      - name: Build and push
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          git remote prune origin
          git push --force-with-lease heroku :refs/heads/main